config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :create_meals


  root 'home#index'
  get  'customer_case' => 'home#customer_case', as: :customer_case
  get  'retailer_case' => 'home#retailer_case', as: :retailer_case

  get 'customer' => 'customer#customer', as: :customer
  get 'meals' => 'customer#meals', as: :meals

  get 'restaurant' => 'restaurant#restaurant', as: :restaurant
  get 'dashboard' => 'restaurant#dashboard', as: :dashboard
  get 'list_meal' => 'restaurant#list_meal', as: :list_meal
  get 'current_meals' => 'restaurant#current_meals', as: :current_meals
  get 'current_ingredients' => 'restaurant#current_ingredients', as: :current_ingredients

  get 'organization' => 'organization#organization', as: :organization
  get 'thankyou' => 'organization#thankyou', as: :thankyou

  get 'sign_up' => 'sign_up#sign_up', as: :sign_up

end

app/models/create_meal.rb
class CreateMeal < ActiveRecord::Base
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    def home
    end

    def sign_up
    end

    def customer
    end

    def restaurant
    end

    def organization
    end

end

app/controllers/create_meals_controller.rb
class CreateMealsController < ApplicationController
  before_action :set_create_meal, only: [:show, :edit, :update, :destroy]

  # GET /create_meals
  # GET /create_meals.json
  def index
    @create_meals = CreateMeal.all
  end

  # GET /create_meals/1
  # GET /create_meals/1.json
  def show
  end

  # GET /create_meals/new
  def new
    @create_meal = CreateMeal.new
  end

  # GET /create_meals/1/edit
  def edit
  end

  # POST /create_meals
  # POST /create_meals.json
  def create
    @create_meal = CreateMeal.new(create_meal_params)

    respond_to do |format|
      if @create_meal.save
        format.html { redirect_to @create_meal, notice: 'Create meal was successfully created.' }
        format.json { render :show, status: :created, location: @create_meal }
      else
        format.html { render :new }
        format.json { render json: @create_meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_meals/1
  # PATCH/PUT /create_meals/1.json
  def update
    respond_to do |format|
      if @create_meal.update(create_meal_params)
        format.html { redirect_to @create_meal, notice: 'Create meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @create_meal }
      else
        format.html { render :edit }
        format.json { render json: @create_meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_meals/1
  # DELETE /create_meals/1.json
  def destroy
    @create_meal.destroy
    respond_to do |format|
      format.html { redirect_to create_meals_url, notice: 'Create meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_meal
      @create_meal = CreateMeal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_meal_params
      params.require(:create_meal).permit(:name, :description, :avatar)
    end
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  def meals
        @create_meals = CreateMeal.all
  end

  def ingredients
    @ingredients = Ingredient.all
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def business_case
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name, :description, :avatar)
    end
end

app/controllers/organization_controller.rb
class OrganizationController < ApplicationController

  def organization
    @Ingredients = Ingredient.all
  end

  
  def thankyou
  end
end

app/controllers/restaurant_controller.rb
class RestaurantController < ApplicationController
  def list_meal
  end

  def restaurant
    @create_meals = CreateMeal.all
    @ingredients = Ingredient.all
  end

  def dashboard
  end

  def current_meals
    @create_meals = CreateMeal.all
  end

  def current_ingredients
    @ingredients = Ingredient.all
  end


end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  def sign_up
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/create_meals_helper.rb
module CreateMealsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/organization_helper.rb
module OrganizationHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/views/create_meals/_form.html.erb
<%= form_for(@create_meal) do |f| %>
  <% if @create_meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@create_meal.errors.count, "error") %> prohibited this create_meal from being saved:</h2>

      <ul>
      <% @create_meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/create_meals/edit.html.erb
<div class="box">
  <h1>Editing Create Meal</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @create_meal %> |
  <%= link_to 'Back', create_meals_path %>
</div>

app/views/create_meals/index.html.erb
<div class="box">
  <p id="notice"><%= notice %></p>

  <h1>Listing Create Meals</h1>
    <hr>
  <!-- <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

  <tbody>
      <% @create_meals.each do |create_meal| %>
        <tr>
          <td><%= image_tag create_meal.avatar.url(:medium) %><td>
          <td><%= create_meal.name %></td>
          <td><%= create_meal.description %></td>
          <td><%= link_to 'Show', create_meal %></td>
          <td><%= link_to 'Edit', edit_create_meal_path(create_meal) %></td>
          <td><%= link_to 'Destroy', create_meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table> -->

  <% @create_meals.each do |create_meal| %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= image_tag create_meal.avatar.url(:medium) %>
        <div class="caption">
          <h3><%= create_meal.name %></h3>
          <p><%= create_meal.description %></p>
          <p>
            <a href="#" class="btn btn-primary" role="button">Purchase Info</a>
            <%= link_to "More Info", create_meal, :class => "btn btn-success"%>
          </p>
        </div>
      </div>
    </div>
  <% end %>


  <br>

  <div class="row center-text">
    <%= link_to ' Create New Meal', new_create_meal_path, :class => "btn btn-primary" %>
  </div>
</div>

app/views/create_meals/new.html.erb
<div class="col-lg-12">
  <div class="box">

    <h1>Create New Meal</h1>

    <%= render 'form' %>

  </br>
    <%= link_to "Back", restaurant_path, :class => "btn btn-success"%>  </div>
</div>

app/views/create_meals/show.html.erb
<p id="notice"><%= notice %></p>
<div class="box">
  <p>
    <%= image_tag @create_meal.avatar.url(:medium) %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @create_meal.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @create_meal.description %>
  </p>


  <%= link_to 'Edit', edit_create_meal_path(@create_meal) %> |
  <%= link_to 'Back', create_meals_path %>
</br></br>
  <%= link_to 'List New Meal', new_create_meal_path, :class => "btn btn-danger" %>

</div>

app/views/customer/customer.html.erb
<div class="box center-text">
  <h1>Customer</h1>
</div>

</br>

<div class="center-text col-lg-12">
    <div class="box">
        <!-- <form>
          <fieldset class="form-group">
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Username">
          </fieldset>
          <fieldset class="form-group">
            <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Password">
          </fieldset>
        </form>
        <input class="btn btn-primary" type="submit" value="Submit">
        <%= link_to "Sign Up", sign_up_path(@sign_up), :class => "btn btn-success"%>
      -->

      <h2>Welcome to Kana</h2>
      <hr>

        </br>
      <%= link_to "Meals", meals_path(@meals), :class => "btn btn-primary"%>
      <%= link_to "Ingredients", ingredients_path(@ingredients), :class => "btn btn-success"%>
    </div>
</div>

app/views/customer/ingredients.html.erb
<div class="box">
    <h3>Available Ingredient Packages</h3>
    <hr>
        <%= link_to 'Back', ingredient_path, :class => "btn btn-success" %>
</div>

 <div>
     <div class="col-lg-4">
       <table>
         <tbody>
             <% @ingredients.each do |ingredient| %>
                   <tr>
                     <div class="center-text">
                       <div class="thumbnail">
                         <%= image_tag ingredient.avatar.url(:thumb) %>
                         <h3><%= ingredient.name %></h3>
                         <p><%= ingredient.description %></p>
                         <%= link_to "Purchase", thankyou_path(@organization), :class => "btn btn-primary"%>
                       </div>
                     </div>
                   </tr>
             <% end %>
         </tbody>
     </table>
   </div>
</div>

<div class="col-lg-8">
 <div class="vertical">
   <%= image_tag ("map.png")%>
 </div>

</div>

app/views/customer/meals.html.erb
  <div class="box">
        <h3>Available Meals</h3>
<hr>
    <%= link_to 'Back', customer_path, :class => "btn btn-success" %>
  </div>

        <div class="col-lg-4">
          <table>
              <tbody>
                  <% @create_meals.each do |create_meal| %>
                        <tr>
                          <div class="center-text">
	                          <div class="thumbnail">
		                          <%= image_tag create_meal.avatar.url(:thumb) %>
		                          <h3><%= create_meal.name %></h3>
		                          <p><%= create_meal.description %></p>

                              <%= link_to "Purchase", thankyou_path(@organization), :class => "btn btn-primary"%>
	                          </div>
	                      </div>
                      </tr>
                  <% end %>
              </tbody>
          </table>
        </div>

        <div class="col-lg-8">
          <div class="vertical">
            <%= image_tag ("map.png")%>
          </div>

        </div>

app/views/home/customer_case.html.erb
<div class="box" style="text-align:center">
    <h1 style="padding-top: 100px">Customer's Use Case</h1>
  <hr>
        <%= image_tag("biz_case/kana_users.png") %>

      </br></br>
      <%= link_to "Back Home", root_path(@home), :class => "btn btn-primary" %>
</div>

app/views/home/index.html.erb
<div class="box" style="text-align:center">
    <div style="padding-top: 75px"><%= image_tag ("mainlogo.png"), :height => "80%"%></div>
    <h1 style="padding-top: 100px">Welcome to Kana</h1>
  <hr>

  <div>
      <h2>About</h2>

      <p>Kana is a revolutionary platform for businesses such as
        Restaurants and Grocery Stores to sell discounted food to customers that would normally get thrown away.

        Every year 1.3 Billion Tons of food gets thrown away globally.
        This food loss is highly due to prepared foods not getting sold in market, whether it be pricing or availability.

        Not only could this food be sold to consumers at a discounted price,
        but it could also be donated to charity organizations local to the respecitve businesses</p>

        <p>Kana hopes to combat the issue of food loss by allowing consumers to purchase discounted foods,
        if these foods are not sold, then they are donated to local charity organzations</p>
   </div>

   <hr>

   <div>
     <h2>Business Case</h2>
        <p>Please click the buttons below to view the use case for customers and retailers</p>
        <%= link_to "Customer Case", customer_case_path, :class => "btn btn-primary" %>
        <%= link_to "Retailer Case", retailer_case_path, :class => "btn btn-success" %>
    </div>
</div>

app/views/home/retailer_case.html.erb
<div class="box" style="text-align:center">
    <h1 style="padding-top: 100px">Retailers Use Case</h1>
  <hr>
    <%= image_tag("biz_case/kana_retailers_process.png") %>
      </br></br>
    <%= link_to "Back Home", root_path(@home), :class => "btn btn-primary" %>
</div>

app/views/ingredients/edit.html.erb
<div class="box">

  <h1>Editing Ingredient</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @ingredient %> |
  <%= link_to 'Back', ingredients_path %>
</div>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box">
      <h3>Available Ingredient Packages</h3>
      <hr>
          <%= link_to 'Back', customer_path, :class => "btn btn-success" %>
</div>

   <div>
       <div class="col-lg-4">
         <table>
           <tbody>
               <% @ingredients.each do |ingredient| %>
                     <tr>
                       <div class="center-text">
                         <div class="thumbnail">
                           <%= image_tag ingredient.avatar.url(:thumb) %>
                           <h3><%= ingredient.name %></h3>
                           <p><%= ingredient.description %></p>
                           <%= link_to "Purchase", thankyou_path(@organization), :class => "btn btn-primary"%>
                         </div>
                       </div>
                     </tr>
               <% end %>
           </tbody>
       </table>
     </div>
 </div>

 <div class="col-lg-8">
   <div class="vertical">
     <%= image_tag ("map.png")%>
   </div>

 </div>

app/views/ingredients/new.html.erb
<div class="box">
  <h1>Create New Ingredient Package</h1>

  <%= render 'form' %>
</br>
  <%= link_to "Back", restaurant_path, :class => "btn btn-success"%>
</div>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>
<div class="box">

  <p>
    <%= image_tag @ingredient.avatar.url(:medium) %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= @ingredient.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @ingredient.description %>
  </p>

  <%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
  <%= link_to 'Back', ingredients_path %>
  
</br></br>
  <%= link_to 'List New Ingredients', new_ingredient_path, :class => "btn btn-danger" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kana</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <!-- <%= link_to 'Kana', root_path(@home), class: "navbar-brand" %> -->
          <div style="padding-top: 10px"><%= link_to image_tag("kanalogo.png"), root_path(@home)%></div>


        </div>


          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-chevron-down"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Home', root_path(@home) %></li>
                <li><%= link_to 'Customer', customer_path(@customer) %></li>
                <li><%= link_to 'Restaurant', restaurant_path(@restaurant) %></li>
                <li><%= link_to 'Organization', organization_path(@organzation) %></li>
                <!-- <li role="separator" class="divider"></li>
                <li><%= link_to 'Sign Up', sign_up_path(@sign_up) %></li> -->
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>




  <body>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/organization/organization.html.erb
<div class="box center-text">
  <h1>Organization</h1>
</div>

</br>

<div class="center-text col-lg-4 col-lg-offset-4">
  <div class="box">

          <hr>
            <h2>Available Meals</h2>
          <hr>

          <div class="row">
<div>
                <div class="thumbnail">
                <%= image_tag ("https://images.unsplash.com/photo-1453831362806-3d5577f014a4?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&w=1080&fit=max&s=a66d195cf88523bb351e921b6e61aadc") %>
                <div class="caption">
                  <h3>Half Foods</h3>
                  <p>10 Mediterranean Meals</p>
                  <p><%= link_to "Purchase", thankyou_path(@organization), :class => "btn btn-primary"%></p>
                </div>
              </div>
            </div>

            <div>
              <div class="thumbnail">
                <%= image_tag ("https://images.unsplash.com/photo-1458642849426-cfb724f15ef7?crop=entropy&dpr=2&fit=crop&fm=jpg&h=800&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450") %>
                <div class="caption">
                  <h3>Pizza Shack</h3>
                  <p>5 Lg Pepperoni Pizzas</p>
                  <p><%= link_to "Purchase", thankyou_path(@organization), :class => "btn btn-primary"%></p>
                </div>
              </div>
            </div>

            <div>
              <div class="thumbnail">
                <%= image_tag ("https://images.unsplash.com/reserve/jCCsCae7RwCDOKTCA2Ji_reggeli%20-%20sonk%C3%A1s%20szendvics.JPG?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&w=1080&fit=max&s=71d324d12cd9a76e457b2bfebb192e29") %>
                <div class="caption">
                  <h3>Savers Grocery</h3>
                  <p>8 Cuban Sandwiches</p>
                  <p><%= link_to "Purchase", thankyou_path(@organization), :class => "btn btn-primary"%></p>
                </div>
              </div>
            </div>
          </div>

          <div class="row">
            <div>
              <div class="thumbnail">
                <%= image_tag ("https://images.unsplash.com/photo-1458130535563-1729c33181cd?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&w=1080&fit=max&s=c65827c930850a8029fc5370fdbc9017") %>
                <div class="caption">
                  <h3>BBQ Hut</h3>
                  <p>6 Sausage & Rice Plates</p>
                  <p><%= link_to "Purchase", thankyou_path(@organization), :class => "btn btn-primary"%></p>
                </div>
              </div>
            </div>

            <div>
              <div class="thumbnail">
                <%= image_tag ("https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&w=1080&fit=max&s=dbbb9cff84744dd5ee12ce715b098f48") %>
                <div class="caption">
                  <h3>Pho Palace</h3>
                  <p>7 Beef Pho Soups</p>
                  <p><%= link_to "Purchase", thankyou_path(@organization), :class => "btn btn-primary"%></p>
                </div>
              </div>
            </div>

            <div>
              <div class="thumbnail">
                <%= image_tag ("https://images.unsplash.com/reserve/oMRKkMc4RSq7N91OZl0O_IMG_8309.jpg?crop=entropy&dpr=2&fit=crop&fm=jpg&h=800&ixjsv=2.1.0&ixlib=rb-0.3.5&q=50&w=1450") %>
                <div class="caption">
                  <h3>Tomato Garden</h3>
                  <p>12 Blue Potato Salads</p>
                  <p><%= link_to "Purchase", thankyou_path(@organization), :class => "btn btn-primary"%></p>
                </div>
              </div>
            </div>
          </div>
          <%= link_to "Back Home", root_path(@home), :class => "btn btn-primary" %>

    </div>

  </div>
</div>

app/views/restaurant/current_ingredients.html.erb
<p id="notice"><%= notice %></p>

  <div class="box">
      <h1>Current Listed Ingredients</h1>
        <hr>
      <div>
        <%= link_to 'Create New Ingredient Package', new_ingredient_path, :class => "btn btn-primary" %>
      </div>
        <hr>
  <div>
      <% @ingredients.each do |ingredient| %>
          <div class="thumbnail">
            <%= image_tag ingredient.avatar.url(:medium) %>
            <div class="caption">
              <h3><%= ingredient.name %></h3>
              <p><%= ingredient.description %></p>
              <p>
                <%= link_to 'Preview', ingredient %>
              </br></br>
                <%= link_to 'Edit', edit_ingredient_path(ingredient) %> |
                <%= link_to 'Delete', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %>
              </p>
            </div>
          </div>
      <% end %>
      <br>
  </div>

  <%= link_to "Back", restaurant_path, :class => "btn btn-success"%>

</div>

app/views/restaurant/current_meals.html.erb
<p id="notice"><%= notice %></p>

  <div class="box">
      <h1>Current Listed Meals</h1>
        <hr>
      <div>
        <%= link_to 'Create New Meal', new_create_meal_path, :class => "btn btn-primary" %>
      </div>
        <hr>
  <div>
      <% @create_meals.each do |create_meal| %>
          <div class="thumbnail">
            <%= image_tag create_meal.avatar.url(:medium) %>
            <div class="caption">
              <h3><%= create_meal.name %></h3>
              <p><%= create_meal.description %></p>
              <h6>
              <%= link_to 'Preview', create_meal %>
            </br></br>
              <%= link_to 'Edit', edit_create_meal_path(create_meal) %> |
              <%= link_to 'Delete', create_meal, method: :delete, data: { confirm: 'Are you sure?' } %>
              </h6>
            </div>
          </div>
      <% end %>
      <br>
  </div>

  <%= link_to "Back", restaurant_path, :class => "btn btn-success"%>

</div>

app/views/restaurant/dashboard.html.erb
<div class="box">
  <div class="center-text">
    <h1>Dashboard</h1>
  </div>
</div>

<div class="box">
  <%= image_tag ("dashboard.gif") %>
</br></br>
  <%= link_to "Back", restaurant_path, :class => "btn btn-success"%>
</div>

app/views/restaurant/restaurant.html.erb
<div class="box" >
    <div>
        <h1>Restaurant</h1>
    </div>
<hr>
</div>

<div class="col-lg-12">
  <div class="box">
    <div>
         <h4>Dashboard</h4>
          <%= link_to 'Go To Dashboard', dashboard_path, :class => "btn btn-success" %>
    </div>
</div>

<div class="col-lg-6">
    <div class="box">
          <h4>Meals</h4>
            <%= link_to 'Show Current Meals', current_meals_path, :class => "btn btn-primary" %>
            <%= link_to 'List New Meal', new_create_meal_path, :class => "btn btn-danger" %>
    </div>
</div>


<div class="col-lg-6">
    <div class="box">
        <h4>Ingredients</h4>
          <%= link_to 'Show Current Ingredients', current_ingredients_path, :class => "btn btn-primary" %>
          <%= link_to 'List New Ingredients', new_ingredient_path, :class => "btn btn-danger" %>
    </div>
</div>

</div>


<!-- <div class="center-text col-lg-6">
              <h4>Current Meals</h4>
                      <table>
                          <tbody>
                              <% @create_meals.each do |create_meal| %>
                                    <tr>
                                      <div class="col-md-6 col-md-offset-3">
                                      <div class="thumbnail">

                                      <%= image_tag create_meal.avatar.url(:thumb) %>
                                      <p><%= create_meal.name %></p>
                                      <p><%= create_meal.description %></p>

                                      <%= link_to 'Show', create_meal %></br>
                                      <%= link_to 'Edit', edit_create_meal_path(create_meal) %> |
                                      <%= link_to 'Destroy', create_meal, method: :delete, data: { confirm: 'Are you sure?' }%>
                                    </div>
                                  </tr>
                              <% end %>
                          </tbody>
                      </table>
                </div>
</div>



<div>
              <h4>Current Ingredients</h4>
                      <table>
                          <tbody>
                              <% @ingredients.each do |ingredient| %>
                                    <tr>
                                      <div class="col-md-6 col-md-offset-3">
                                      <div class="thumbnail">

                                      <%= image_tag ingredient.avatar.url(:thumb) %>
                                      <p><%= ingredient.name %></p>
                                      <p><%= ingredient.description %></p>

                                      <%= link_to 'Show', ingredient %></br>
                                      <%= link_to 'Edit', edit_ingredient_path(ingredient)%> |
                                      <%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %>
                                    </div>
                                  </tr>
                              <% end %>
                          </tbody>
                      </table>
                </div>
</div> -->